# Spring properties
spring:
  application:
     name: salesexpress-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/salesexpress
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver    

error:
  path: /error

server:
  port: 2222   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION