spring:
  application:
    name: client-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false      
  datasource:
    url: "jdbc:postgresql://localhost:5432/salesexpress"
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver    

error:
  path=/error

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 4444
